### ISSUE TITLE
How is the performance?

### ISSUE THREAD

**Issue by HouzuoGuo** [oncue/journal#5]
Have you done performance benchmark on the library? How's the CPU usage and throughput compared to a conventional logging library?

**Comment by runarorama** [comment]
We have done some preliminary benchmarking. Journal is really just a very thin wrapper around SLF4J.

Any difference is strictly because of the asynchronous nature of Journal. Journal has a dedicated thread consuming the log queue, so if all your CPUs are saturated this will actually be slower, not faster. Using SLF4J with `AsyncAppender`, you should be able to get exactly the same performance profile.

**Comment by runarorama** [comment]
In addition, the macros ensure that if you have a particular log level turned off, the logger calls will be completely removed from the compiled code. So e.g. your debug log statements will have no overhead in production.

**Comment by runarorama** [comment]
Published the latency benchmark in https://github.com/oncue/journal/commit/7b8d45c84188337a883ad7d96d40ffa776943e1e

Running it on my laptop gives the following timings:

```
Journal:
  min: 14 ns
  max: 87724 ns
  avg: 49.300918 ns
SLF4J:
  min: 1243 ns
  max: 32737417 ns
  avg: 4592.998692 ns
```

So Journal reduces the latency of logging by roughly two orders of magnitude.
